django_demo/django_demo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView


urlpatterns = [
    path('library/', include(('library.urls', 'library'), namespace='library')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='library/', permanent=False)),
    path('tinymce/', include('tinymce.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_demo/library/urls.py
from django.urls import path

from . import views



urlpatterns = [
    path('', views.index, name='index'),
    path('uzrasai/', views.UzrasasListView.as_view(), name='uzrasai'),
    path('uzrasai/<int:pk>', views.UzrasasDetailView.as_view(), name='uzrasas'),
    path('kategorijos/', views.kategorijos, name='kategorijos'),
    path('kategorijos/<int:kategorija_id>', views.kategorija, name='kategorija'),
    path('search/', views.search, name='search'),
    path('filter/', views.filter, name='filter'),
    path('register/', views.register, name='register'),
    path('profilis/', views.profilis, name='profilis'),
    path('myuzrasai/', views.LoanedUzrasaiByUserListView.as_view(), name='myuzrasai'),
    path('myuzrasai/<int:pk>', views.UzrasasByUserDetailView.as_view(), name='my-uzrasas'),
    path('myuzrasai/new', views.UzrasasByUserCreateView.as_view(), name='my-uzrasas-new'),
    path('myuzrasai/<int:pk>/update', views.UzrasasByUserUpdateView.as_view(), name='my-uzrasas-update'),
    path('myuzrasai/<int:pk>/delete', views.UzrasasByUserDeleteView.as_view(), name='my-uzrasas-delete'),
    path('mykategorijos/', views.LoanedKategorijosiByUserListView.as_view(), name='mykategorijos'),
    path('mykategorijos/<int:pk>', views.KategorijaByUserDetailView.as_view(), name='my-kategorija'),
    path('mykategorijos/new', views.KategorijaByUserCreateView.as_view(), name='my-kategorija-new'),
    path('mykategorijos/<int:pk>/update', views.KategorijaByUserUpdateView.as_view(), name='my-kategorija-update'),
    path('mykategorijos/<int:pk>/delete', views.KategorijaByUserDeleteView.as_view(), name='my-kategorija-delete'),
]

django_demo/library/models.py
import uuid
from django.db import models
from tinymce.models import HTMLField
from PIL import Image
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User




class Uzrasas(models.Model):
    title = models.CharField('Pavadinimas', max_length=200)
    kategorija = models.ForeignKey('Kategorija', on_delete=models.SET_NULL, null=True, related_name='uzrasai')
    summary = models.TextField('Tekstas', max_length=1000)
    #genre = models.ManyToManyField('Genre')
    cover = models.ImageField('Viršelis', default="default.png", upload_to='covers')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Užrašas'
        verbose_name_plural = 'Užrašai'

  

    def kategorija_name(self):
        if self.kategorija:
            return self.kategorija.first_name
        else:
            return '-'

   


class Kategorija(models.Model):
   
    first_name = models.CharField('Vardas', max_length=100)
    #description = models.TextField('Aprašymas', max_length=2000, default='')
    description = HTMLField()

    def __str__(self):
        return f'{self.first_name}'

    def display_uzrasai(self):
        return ', '.join(uzrasas.title for uzrasas in self.uzrasai.all()[:3])

    display_uzrasai.short_description = 'Užrašai'


class Profilis(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nuotrauka = models.ImageField(default="default.png", upload_to="profile_pics")

    def __str__(self):
        return f"{self.user.username} profilis"

    class Meta:
        verbose_name = 'Profilis'
        verbose_name_plural = 'Profiliai'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.nuotrauka.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.nuotrauka.path)

django_demo/library/forms.py
from socket import fromshare
from xml.dom import ValidationErr
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from .models import Profilis, Uzrasas, Kategorija

class RegistrationForm(forms.Form):
    username = forms.CharField(max_length=100)
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)
    
    def clean_username(self):
        data = self.cleaned_data['username']
        if User.objects.filter(username=data).exists():
            raise ValidationError(f'Vartotojo vardas {data} užimtas!')
        return data

    def clean_email(self):
        data = self.cleaned_data['email']
        if User.objects.filter(email=data).exists():
            raise ValidationError(f'El. paštas {data} užimtas!')
        return data

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data['password']
        password2 = cleaned_data['password2']
        if password != password2:
            raise ValidationError('Slaptažodžiai nesutampa')

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfilisUpdateForm(forms.ModelForm):
    class Meta:
        model = Profilis
        fields = ['nuotrauka']

django_demo/library/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse 
from django.http import HttpResponse
from django.views import generic
from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib.auth.forms import User
from django.views.decorators.csrf import csrf_protect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse, reverse_lazy
from .models import Uzrasas, Kategorija
from .forms import RegistrationForm, UserUpdateForm, ProfilisUpdateForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView

 

def index(request):
    num_uzrasai = Uzrasas.objects.all().count()
    num_kategorijos = Kategorija.objects.count()
    
    num_visits = request.session.get('num_visits', 1)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_uzrasai': num_uzrasai,
        'num_kategorijos': num_kategorijos,
        'num_visits': num_visits,
    }

    return render(request, 'library/index.html', context=context)


class UzrasasListView(generic.ListView):
    model = Uzrasas
    context_object_name = 'my_uzrasas_list'
    template_name = 'library/uzrasas_list.html'


class UzrasasDetailView(generic.DetailView):
    model = Uzrasas
    template_name = 'library/uzrasas_detail.html'


def kategorijos(request):
    paginator = Paginator(Kategorija.objects.all(), 2)
    page_number = request.GET.get('page')
   
    paged_kategorijos = paginator.get_page(page_number)
    context = {
        'kategorijos': paged_kategorijos
    }
    return render(request, 'library/kategorijos.html', context)


def kategorija(request, kategorija_id):

    selected_kategorija = get_object_or_404(Kategorija, pk=kategorija_id)
    context = {
        'kategorija': selected_kategorija
    }
    return render(request, 'library/kategorija.html', context)


def search(request):
    query = request.GET.get('query')
    search_results = Uzrasas.objects.filter(Q(title__icontains=query) | Q(summary__icontains=query))
    return render(request, 'library/search.html', {'uzrasai': search_results, 'query': query})

def filter(request):
    query = request.GET.get('query')
    search_results = Kategorija.objects.filter(Q(first_name__icontains=query))
    return render(request, 'library/filter.html', {'kategorijos': search_results, 'query': query})

def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            User.objects.create_user(
                username=form.cleaned_data['username'],
                email=form.cleaned_data['email'],
                password=form.cleaned_data['password'])
            messages.info(request, 'Registracija sėkminga')
            return redirect('library:register')
        
    else:
         form = RegistrationForm()
    return render(request, 'library/register.html', {'form': form})
@login_required
def profilis(request):
        if request.method == 'POST':
            u_form = UserUpdateForm(request.POST, instance=request.user)
            p_form = ProfilisUpdateForm(request.POST, request.FILES, instance=request.user.profilis)
            if u_form.is_valid() and p_form.is_valid():
                u_form.save()
                p_form.save()
                messages.success(request, f"Profilis atnaujintas")
                return redirect('library:profilis')
        else:
            u_form = UserUpdateForm(instance=request.user)
            p_form = ProfilisUpdateForm(instance=request.user.profilis)
        context = {
            'u_form': u_form,
            'p_form': p_form,
        }
        return render(request, 'library/profilis.html', context=context)

class LoanedUzrasaiByUserListView(LoginRequiredMixin,generic.ListView):
    model = Uzrasas
    context_object_name = 'uzrasai'
    template_name ='library/user_uzrasai.html'

    def get_queryset(self):
      return Uzrasas.objects.filter(title=self.request.user)


class UzrasasByUserDetailView(LoginRequiredMixin, generic.DetailView):
    model = Uzrasas
    template_name = 'library/user_uzrasas.html'


class UzrasasByUserCreateView(LoginRequiredMixin, generic.CreateView):
    model = Uzrasas
    fields = ['title', 'kategorija', 'summary', 'cover']
    success_url = reverse_lazy('library:myuzrasai')
    template_name = 'library/user_uzrasas_form.html'
    

    def get_absolute_url(self):
        """Nurodo konkretaus aprašymo galinį adresą"""
        return reverse('uzrasas-detail', args=[str(self.id)])


class UzrasasByUserUpdateView(LoginRequiredMixin,  generic.UpdateView):
    model = Uzrasas
    fields = ['title', 'kategorija', 'summary', 'cover']
    success_url = reverse_lazy('library:myuzrasai')
    template_name = 'library/user_uzrasas_form.html'
   
   

class UzrasasByUserDeleteView(LoginRequiredMixin,  generic.DeleteView):
    model = Uzrasas
    success_url = reverse_lazy('library:myuzrasai')
    template_name = 'library/user_uzrasas_delete.html'

  
class KategorijaByUserDetailView(LoginRequiredMixin, generic.DetailView):
    model = Kategorija
    template_name = 'library/user_kategorija.html'


class LoanedKategorijosiByUserListView(LoginRequiredMixin,generic.ListView):
    model = Kategorija
    context_object_name = 'kategorijos'
    template_name ='library/user_kategorijos.html'

    def get_queryset(self):
        return Kategorija.objects.filter(first_name=self)
   
class KategorijaByUserCreateView(LoginRequiredMixin, generic.CreateView):
    model = Kategorija
    fields = ['first_name', 'description']
    success_url = reverse_lazy('library:mykategorijos')
    template_name = 'library/user_kategorija_form.html'
  
class KategorijaByUserUpdateView(LoginRequiredMixin,  generic.UpdateView):
    model = Kategorija
    fields =['first_name', 'description']
    success_url = reverse_lazy('library:mykategorijos')
    template_name = 'library/user_kategorija_form.html'

class KategorijaByUserDeleteView(LoginRequiredMixin,  generic.DeleteView):
    model = Kategorija
    success_url = reverse_lazy('library:mykategorijos')
    template_name = 'library/user_kategorija_delete.html'

django_demo/library/templates/library/index.html
{% extends "base.html" %}

{% block content %}
  <h1>VARTOTOJŲ UŽRAŠAI</h1>
  <p>Šiuo metu yra prikurta:</p>
  <ul>
    <li><strong>Užrašų:</strong> {{ num_uzrasai }}</li>
    <li><strong>Kategorijų:</strong> {{ num_kategorijos }}</li>
  </ul>
  <p>Čia lankausi {{ num_visits }}-ą kartą.</p>
{% endblock %}

django_demo/library/templates/library/profilis.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profilis.nuotrauka.url }}">
        <div class="media-body">
          <h2 class="account-heading">{{ user.username }}</h2>
          <p class="text-secondary">{{ user.email }}</p>
        </div>
      </div>
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Profilio info</legend>
            {{ u_form|crispy }}
            {{ p_form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Atnaujinti</button>
        </div>
        </form>
    </div>
{% endblock content %}

django_demo/library/templates/library/register.html
{% extends "base.html" %}

{% block content %}
    {% if messages %}
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                <div class="alert alert-danger" role="alert">
                    {{ message }}
                </div>
            {% else %}
                <div class="alert alert-info" role="alert">
                    {{ message }}
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}

    <div class="container register">
        <h3>Registracija</h3><br/>
       
        <form  method="post">
           {% csrf_token %}
           {{ form.non_field_errors}}
           {% for field in form %}
                <div class="form-group">
                    {{ field.errors }}
                    {{ field.label_tag }} {{ field}}
                </div>
                {% endfor %}
         
           <input type="submit" value="Spausti">
        </form>
        <p>Jeigu užsiregistravote anksčiau, <a href="{% url 'login' %}"><strong>prisijunkite.</strong></a></p>
    </div>

{% endblock %}

django_demo/library/templates/library/search.html
{% extends "base.html" %}

{% block content %}
  <h1>Paieškos pagal "{{query}}" rezultatai:</h1>

  {% if uzrasai %}
  <ul>
    {% for uzrasas in uzrasai %}
      <li>
        <a href="{% url 'library:uzrasas' uzrasas.id %}">{{ uzrasas.title }}</a> ({{uzrasas.kategorija}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>Oops. Nieko neradome :(</p>
  {% endif %}

  {% endblock %}

django_demo/library/templates/library/user_kategorija_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Ištrinti užrašą</legend>
            <h2>Ar tikrai norite ištrinti "{{ kategorija.first_name }}"?</h2>
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-danger" type="submit">Taip, ištrinti</button>
            <a class="btn btn-outline-secondary" href="{% url 'library:kategorijos' %}">Atšaukti</a>
        </div>
    </form>
    </div>
{% endblock content %}

django_demo/library/templates/library/user_kategorija_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Nauja kategorija</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Išsaugoti</button>
        </div>
    </form>
    </div>
{% endblock content %}

django_demo/library/templates/library/user_kategorijos.html
{% extends "base.html" %}
{% block content %}
    <h1>Atlikti pokyčiai su kategorijomis</h1>   
 {% endblock %}

django_demo/library/templates/library/user_uzrasai.html
{% extends "base.html" %}

{% block content %}
    <h1>Atlikti pokyčiai su užrašais</h1>   
 {% endblock %}

django_demo/library/templates/library/user_uzrasas.html
{% extends "base.html" %}

{% block content %}
    <h1>Mano užrašai:</h1>
    <hr>
        <ul>
        <li><strong >Pavadinimas: {{object.uzrasas.title}}</strong></li>
        <li><strong>Kategorija:</strong> {{ object.kategorija.first_name }}</li>
        <li><strong>Aprašas:</strong> {{ object.kategorija.description }}</li>
        <li><strong>Nuotrauka:</strong> {{ object.uzrasas.cover }}</li>

        <br/>
      </li>
    </ul>
{% endblock %}

django_demo/library/templates/library/user_uzrasas_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Ištrinti užrašą</legend>
            <h2>Ar tikrai norite ištrinti "{{ uzrasas.title }}"?</h2>
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-danger" type="submit">Taip, ištrinti</button>
            <a class="btn btn-outline-secondary" href="{% url 'library:uzrasai' %}">Atšaukti</a>
        </div>
    </form>
    </div>
{% endblock content %}

django_demo/library/templates/library/user_uzrasas_form.html
{% extends "base.html" %}

{% block content %}
<div class="content-section">
        <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
       
            <legend class="border-bottom mb-4">Naujai kuriamas užrašas</legend>
            {{ form.non_field_errors}}
            {% for field in form %}
                 <div class="form-group">
                     {{ field.errors }}
                     {{ field.label_tag }} {{ field}}
                 </div>
                 {% endfor %}
       
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Išsaugoti</button>
     </div>
    </form>
    </div>
{% endblock content %}

django_demo/library/templates/library/uzrasai.html
{% extends "base.html" %}

{% block content %}
    {% for uzrasas in uzrasai %}
        <p>
            <a href="{% url 'library:uzrasas' uzrasas.id %}">{{ uzrasas.title }}</a>
        </p>
    {% endfor %}
      
{% endblock %}

django_demo/library/templates/library/uzrasas_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ uzrasas.title }}</h1>

  <p><strong>Kategorija:</strong> <a href="{% url 'library:kategorija' uzrasas.kategorija.pk %}">{{ uzrasas.kategorija }}</a></p>
  <p><strong>Tekstas:</strong> {{ uzrasas.summary }}</p>
  <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'library:my-uzrasas-update' uzrasas.id %}">Redaguoti</a>
  <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'library:my-uzrasas-delete' uzrasas.id %}">Ištrinti</a>

  <div style="margin-left:20px;margin-top:20px">
       

  </div>
{% endblock %}

django_demo/library/templates/library/uzrasas_list.html
{% extends "base.html" %}

{% block content %}
    <h1>Užrašai</h1></br>
    <a class="btn1" href="{% url 'library:my-uzrasas-new' %}" role="button">Kurkime naują užrašą</a>
    {% if my_uzrasas_list %}
    <div class="row">
    {% for uzrasas in my_uzrasas_list %}

            <div class="colflexalignitemsstretch">
            <div class="card mb-4 shadow-sm">
                {% if uzrasas.cover %}
                    <img src="{{ uzrasas.cover.url }}" width="200" height="300" class="card-img-top" alt="...">
                {% else %}
                    <img src="https://via.placeholder.com/200x300" class="card-img-top">
                {% endif %}
                <div class="card-body">
                <h6 class="card-subtitle mb-2 text-muted">{{ my_uzrasas_list.kategorija }}</h6>
                <p class="card-text"><a href="{{ uzrasas.id }}">{{ uzrasas.title }}</a></p>
             
                </div>
            </div>
            </div>
        {% endfor %}
        </div>
       
    {% else %}
        <p>Užrašų niekas neįrašė....</p>
    {% endif %}

{% endblock %}