django_demo/django_demo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView


urlpatterns = [
    path('library/', include(('library.urls', 'library'), namespace='library')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='library/', permanent=False)),
    path('tinymce/', include('tinymce.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_demo/library/urls.py
from django.urls import path

from . import views



urlpatterns = [
    path('', views.index, name='index'),
    path('uzrasai/', views.UzrasasListView.as_view(), name='uzrasai'),
    path('uzrasai/<int:pk>', views.UzrasasDetailView.as_view(), name='uzrasas'),
    path('kategorijos/', views.kategorijos, name='kategorijos'),
    path('kategorijos/<int:kategorija_id>', views.kategorija, name='kategorija'),
    path('search/', views.search, name='search'),
    path('filter/', views.filter, name='filter'),
    path('register/', views.register, name='register'),
    path('profilis/', views.profilis, name='profilis'),
    path('myuzrasai/', views.LoanedUzrasaiByUserListView.as_view(), name='myuzrasai'),
    path('myuzrasai/<int:pk>', views.UzrasasByUserDetailView.as_view(), name='my-uzrasas'),
    path('myuzrasai/new', views.UzrasasByUserCreateView.as_view(), name='my-uzrasas-new'),
    path('myuzrasai/<int:pk>/update', views.UzrasasByUserUpdateView.as_view(), name='my-uzrasas-update'),
    path('myuzrasai/<int:pk>/delete', views.UzrasasByUserDeleteView.as_view(), name='my-uzrasas-delete'),
    path('mykategorijos/', views.LoanedKategorijosiByUserListView.as_view(), name='mykategorijos'),
    path('mykategorijos/<int:pk>', views.KategorijaByUserDetailView.as_view(), name='my-kategorija'),
    path('mykategorijos/new', views.KategorijaByUserCreateView.as_view(), name='my-kategorija-new'),
    path('mykategorijos/<int:pk>/update', views.KategorijaByUserUpdateView.as_view(), name='my-kategorija-update'),
    path('mykategorijos/<int:pk>/delete', views.KategorijaByUserDeleteView.as_view(), name='my-kategorija-delete'),
]

django_demo/django_demo/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>MANO UŽRAŠAI</title>{% endblock %}
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
 
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'library/style.css' %}">
</head>
<body>
  <main>
 
  <!-- Navigation -->
  <header>
  <div class="navbar">
   
    <div class="container1">
          <div class="navbarauto">
         
               <a class="nav-item" href="{% url 'library:index' %}">Pradžia</a>
                                    
            {% if user.is_authenticated %}
             <div class="nav-item">
              <a class="nav-link" href="{% url 'library:uzrasai' %}">Užrašai</a>
            </div>
            <div class="nav-item">
              <a class="nav-link" href="{% url 'library:kategorijos' %}">Kategorijos</a>
            </div>
                      
            <div class="nav-item">
              <a class="nav-link" href="{% url 'library:profilis' %}">
              <svg class="bi bi-person" width="1.5em" height="1.5em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd" d="M13 14s1 0 1-1-1-4-6-4-6 3-6 4 1 1 1 1h10zm-9.995-.944v-.002.002zM3.022 13h9.956a.274.274 0 00.014-.002l.008-.002c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664a1.05 1.05 0 00.022.004zm9.974.056v-.002.002zM8 7a2 2 0 100-4 2 2 0 000 4zm3-2a3 3 0 11-6 0 3 3 0 016 0z" clip-rule="evenodd"/>
              </svg>
              
              {{ user.get_username }}</a>
            </div>
              <div class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">Atsijungti</a></div>   
            {% else %}
              <div class="nav-item"><a class="nav-link" href="{% url 'login' %}?next={% url 'library:index' %}">Prisijungti</a></div>   
              <div class="nav-item"><a class="nav-link" href="{% url 'library:register' %}">Registruotis</a></div>
            {% endif %}
          </div>
          <div class="navbarauto1">
            <div class="nav-item2">
              <form class="form-inline my-2 my-lg-0" action="{% url 'library:search' %}" method="get">
                <input class="form-control mr-sm-2" type="search" placeholder="Paieška" aria-label="Search" name="query">
                <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Ieškoti</button>
               </form>
              </div>
  
              <div class="nav-item2">
              <form class="form-inline my-2 my-lg-0" action="{% url 'library:filter' %}" method="get">
                <input class="form-control mr-sm-2" type="search" placeholder="Filtras" aria-label="Search" name="query">
                <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Ieškoti</button>
              </form>
              </div>
            </div > 
        
      </div>
    </div>
  </div>
</header>
  <div class="container">
  {% block content %}{% endblock %}
  </div>
</main>
</body>
</html>